name: Build

on: "push"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm t

    - name: Release
      uses: emphori/actions/semantic-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
